### ISSUE TITLE
Superset Integration

### ISSUE THREAD

**Issue by emresemercioglu** [metriql/metriql#10]

**Comment by buremba** [comment]
Superset already integrates with Trino using their Python client. (https://github.com/trinodb/trino-python-client) 

Metriql should just work fine with Trino integration and we can use their [REST API](https://superset.apache.org/docs/rest-api) in order to sync the metrics definitions.

**Comment by buremba** [comment]
It's implemented in master! See the documentation here: https://metriql.com/integrations/bi-tools/superset
