### ISSUE TITLE
Support for dbt+Snowflake key-pair authentication

### ISSUE THREAD

**Issue by ZolotukhinAS** [metriql/metriql#23]
Ensure that metriql can connect to Snowflake via key-pair authentication defined in dbt profile.
See here for [dbt docs](https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile#key-pair-authentication)

**Comment by buremba** [comment]
@ZolotukhinAS , the `metriql:latest` tag in Docker now has this feature, please feel free try to and let me know if you run into any issues. 🤟
