### ISSUE TITLE
tutorial does not work

### ISSUE THREAD

**Issue by danielefrigo** [metriql/metriql#24]
I followed the instructions provided [here](https://metriql.com/tutorial/for-starters), I also executed a "dbt compile" before running metriql in order to generate the manifest.json file.
I'm running metriql thru docker, so my command is:

docker run -v c:\dbt\:/mnt/dbt -v c:\users\frigod\.dbt:/mnt/dbt_profile buremba/metriql:latest run --project-dir /mnt/dbt/metriql_test2 --profiles-dir /mnt/dbt_profile --manifest-json file:/mnt/dbt/metriql_test/target/manifest.json

I then tried connecting to the Trino engine using dbeaver. I can connect, but I cannot see any table (and opening the table list invalidates the connection).

I the tried running metriql generate to understand the issue:

docker run -v c:\dbt\:/mnt/dbt -v c:\users\frigod\.dbt:/mnt/dbt_profile buremba/metriql:latest generate --project-dir /mnt/dbt/metriql_test2 --profiles-dir /mnt/dbt_profile

and the result is:

Done creating 0 aggregate dbt models.

**Comment by buremba** [comment]
Hey @danielefrigo , It looks like you used [`generate`](https://metriql.com/metriql-cli/generate) instead of [`serve`](https://metriql.com/metriql-cli/serve) (previously `run`), could you please try to run `metriql serve`?

**Comment by danielefrigo** [comment]
I tried both, but without success.
Today I donwload the latest version of the docker image and tried again:

1. dbt init
2. create source.yml file
3. dbt compile (to generate the manifest.json file)
4. docker run -v c:\dbt\:/mnt/dbt -v c:\users\frigod\.dbt:/mnt/dbt_profile buremba/metriql:latest serve --project-dir /mnt/dbt/metriql_test2 --profiles-dir /mnt/dbt_profile --manifest-json file:/mnt/dbt/metriql_test/target/manifest.json --jdbc

No errors from the command itself, but wheen I try to connect thru dbeaver I can connect, but when browsing table I get:

SQL Error: Error executing query
  Error executing query
  Error executing query
    java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:5656
    java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:5656
      Failed to connect to localhost/0:0:0:0:0:0:0:1:5656
      Failed to connect to localhost/0:0:0:0:0:0:0:1:5656
        Connection refused: connect
        Connection refused: connect

Then I tried also:
docker run -v c:\dbt\:/mnt/dbt -v c:\users\frigod\.dbt:/mnt/dbt_profile buremba/metriql:latest generate --project-dir /mnt/dbt/metriql_test2 --profiles-dir /mnt/dbt_profile

and the result is:

Sep 03, 2021 8:06:43 AM ru.yandex.clickhouse.ClickHouseDriver <clinit>
INFO: Driver registered
Deleting directory models/metriql
Done creating 0 aggregate dbt models.

**Comment by buremba** [comment]
It looks like Metriql is not running so Dbeaver is not able to reach the server. Can you please send the output of the following command:

```
docker run -v c:\dbt:/mnt/dbt -v c:\users\frigod.dbt:/mnt/dbt_profile buremba/metriql:latest serve --project-dir /mnt/dbt/metriql_test2 --profiles-dir /mnt/dbt_profile --manifest-json file:/mnt/dbt/metriql_test/target/manifest.json --jdbc
```

Also, does the Docker container exit?

**Comment by danielefrigo** [comment]
This is the output:

Sep 03, 2021 3:23:27 PM ru.yandex.clickhouse.ClickHouseDriver <clinit>
INFO: Driver registered
Sep 03, 2021 3:23:31 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0x0afedaa7] REGISTERED
Sep 03, 2021 3:23:31 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0x0afedaa7] BIND(/127.0.0.1:5656)
Sep 03, 2021 3:23:31 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0x0afedaa7, L:/127.0.0.1:5656] ACTIVE

The container is still running.

**Comment by buremba** [comment]
Ah, OK. You're right. Thanks for the clarification!

It looks like the tutorial doesn't have the correct Docker arguments. Please use the following command:

```
docker run -v c:\dbt:/mnt/dbt -v c:\users\frigod.dbt:/mnt/dbt_profile -p "5656:5656" -e METRIQL_RUN_HOST=0.0.0.0 buremba/metriql:latest serve --project-dir /mnt/dbt/metriql_test2 --profiles-dir /mnt/dbt_profile --manifest-json file:/mnt/dbt/metriql_test/target/manifest.json  --jdbc 
```

I added `-p "5656:5656" -e METRIQL_RUN_HOST=0.0.0.0` so that you can access the Docker container locally. In the meantime, I tried Dbeaver locally to test it out and the settings should look like this:

<img width="1257" alt="CleanShot 2021-09-03 at 18 50 49@2x" src="https://user-images.githubusercontent.com/82745/132033293-766c001c-2c85-4bb2-af07-391c240b3077.png">

**Comment by danielefrigo** [comment]
That's a good step!
Now the connection is working, but I still get errors when I try to browse the tables:

SQL Error: Error executing query
  Error executing query
  Error executing query
    javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
    javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
      Unsupported or unrecognized SSL message
      Unsupported or unrecognized SSL message

On the container log I see:

Sep 03, 2021 4:05:08 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0xb42ce100, L:/0:0:0:0:0:0:0:0%0:5656] RECEIVED: [id: 0x590896b7, L:/172.17.0.2:5656 - R:/172.17.0.1:34862]
Sep 03, 2021 4:05:11 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0xb42ce100, L:/0:0:0:0:0:0:0:0%0:5656] RECEIVED: [id: 0xd1edfab4, L:/172.17.0.2:5656 - R:/172.17.0.1:34866]
Sep 03, 2021 4:05:21 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0xb42ce100, L:/0:0:0:0:0:0:0:0%0:5656] RECEIVED: [id: 0xb697f7db, L:/172.17.0.2:5656 - R:/172.17.0.1:34870]

**Comment by buremba** [comment]
How are you setting up Dbeaver, can you please send a picture similar to mine? It looks like it tries to connect via SSL but since you're in the local environment, SSL is not available. Please note that if you send a password, JDBC requires SSL to be enabled.

**Comment by danielefrigo** [comment]
You're right! The SSL flag was true by default, switching to false the error disappears, but I still cannot see the source I mapped in dbt:

![image](https://user-images.githubusercontent.com/28701043/132174659-106d1ed4-114e-447a-88ac-4b566516f0dc.png)

**Comment by buremba** [comment]
Congrats! If you don't see any table, you probably don't have any metriql datasets yet. Is your dbt project public? For the reference, I realized that the documentation is a bit misleading, you need to have `meta.metriql` property to be set so that metriql can expose it to your data tools. Please see the [relevant documentation](https://metriql.com/tutorial/for-dbt-users). 
We also have a sample project here: https://github.com/metriql/metriql-snowflake-demo-tpch/blob/main/models/schema.yml

**Comment by danielefrigo** [comment]
I got it working! there was a wrong path in my docker run command.
thank you very much for your help (and I hope this will help others willing to start working with this interesting project!)

**Comment by buremba** [comment]
Thanks for being responsive @danielefrigo! It definitely helped, I edited the tutorials based on the feedback that I got from you. :) Feel free to join [our Slack](https://join.slack.com/t/metriql/shared_invite/zt-tz1nzvyd-ker8LGcBQmzrwvfAkFO1qQ) for live support and announcements. :)
