### ISSUE TITLE
Unable to access metriql's local server

### ISSUE THREAD

**Issue by cavernaria** [metriql/metriql#25]
I started metriql, referring to the documentation and the #24 , but I cannot connect to metriql.

The command used to start it (My environment is fish, so the way variables are written may be different).

```bash
docker run -it -v "$DBT_PROJECT_DIR:/root/app" -v "$DBT_PROFILES_DIR:/root/.dbt" -v "$GCLOUD_DIR:/root/.gcloud" -e DBT_PROJECT_DIR=/root/app -p "5656:5656" -e METRIQL_RUN_HOST=0.0.0.0 buremba/metriql:latest serve
```

This is the result of executing the command.

```log
Sep 13, 2021 7:12:45 AM ru.yandex.clickhouse.ClickHouseDriver <clinit>
INFO: Driver registered
Sep 13, 2021 7:12:47 AM com.metriql.service.model.DiscoverService discoverDimensionFieldTypes
INFO: Discovering 6 dimensions of model `model_jaffle_shop_dim_customers`
Sep 13, 2021 7:12:51 AM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0x1fa72a43] REGISTERED
Sep 13, 2021 7:12:51 AM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0x1fa72a43] BIND(/127.0.0.1:5656)
Sep 13, 2021 7:12:51 AM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0x1fa72a43, L:/127.0.0.1:5656] ACTIVE
```

When I try to connect with Dbeaver in this state, the connection itself succeeds (it takes a very long time). However, when I try to check the table list, I get a timeout error.

I also could not connect to it from a web browser (in the YouTube video, you can connect to it at `http://127.0.0.7:5656`, right?

It seems to me that metriql itself is not working correctly. What should I do?

**Comment by buremba** [comment]
Thanks for creating the issue, @cavernia! You're right, it looks like your Metriql server didn't bind to 0.0.0.0 from the Docker container so you can't access it from your local machine. `METRIQL_RUN_HOST` environment variable is removed to `HOST` recently and looks like I forgot to put a deprecation notice. 

I added support for `METRIQL_RUN_HOST` env again, if you clean your Docker cache and run the same Docker command, it should work as expected and the URL in the logs should be `0.0.0.0:5656`.

I edit the other post as well, the CLI should also show you the relevant environment variable but if you update the env as follows, it should work in the future:

```
-e HOST=0.0.0.0
```

**Comment by cavernaria** [comment]
Thanks for the quick reply.
I did what you said and now I have access! Thank you for your help!

**Comment by buremba** [comment]
Great to hear, thanks for letting me know @cavernaria !
