### ISSUE TITLE
Connect via OAuth

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#44]
Hi,

Is it possible to give different users different access? Or is the solution currently that if you have access to Metriql you can access all data that Metriql can access?

Cheers!

**Comment by buremba** [comment]
Yes, we support different ways to manage the authorization and permissions, please see https://metriql.com/metriql-cli/serve/#authorization-and-permission-management

What's your use case, are you planning to use Metriql in an embedded application or internally? Most BI tools don't support OAuth authorization so we currently support JWT token mainly for making Metriql work with single-page applications for embedded analytics use-cases.

**Comment by AndreasTA-AW** [comment]
Yeah, some of the BI Tool support OAuth, and some "only" support it for now. I think Tableau is one of them?

I'm currently just playing around to see if we could store metrics from DBT with the help of Metriql :)

**Comment by buremba** [comment]
BTW, you're correct that Tableau supports OAuth but unfortunately, it doesn't support it for Prestodb which is our query interface: 
<img width="423" alt="CleanShot 2021-11-23 at 18 56 33@2x" src="https://user-images.githubusercontent.com/82745/143058411-120e4ca5-d1a6-4c7b-a51d-7ebbc6d02321.png">

**Comment by AndreasTA-AW** [comment]
Thanks for info
