### ISSUE TITLE
Support `date_trunc` function in MQL

### ISSUE THREAD

**Issue by buremba** [metriql/metriql#45]
We can re-write the query to use the corresponding [timeframe](https://metriql.com/reference/dimension/#timeframes) defined in the data model.
[1](https://metriql.slack.com/archives/C0229LE836K/p1637118539032800)

**Comment by minhlucvan** [comment]
Thanks @buremba for creating this, There are anything that I can do for this. Can I add a function at `ANSISQLMetriqlBridge.functions`?

**Comment by buremba** [comment]
Thanks for the interest! Here are the steps:

1. Add `DATE_TRUNC` function to [RFunction](https://github.com/metriql/metriql/blob/d9534b9df9d516470efff5a6e52068faf37f0c52/src/main/java/com/metriql/warehouse/spi/function/RFunction.kt) that matches Trino's [date_trunc](https://trino.io/docs/current/functions/datetime.html#truncation-function) function.

2. Implement generic method to [`ANSISQLMetriqlBridge.functions`](https://github.com/metriql/metriql/blob/d9534b9df9d516470efff5a6e52068faf37f0c52/src/main/java/com/metriql/warehouse/spi/bridge/ANSISQLMetriqlBridge.kt#L70)

3. Then we implement warehouse-specific dialect. Luckily most of them uses the same standard, please see:

- https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#date_trunc
- https://www.postgresql.org/docs/9.1/functions-datetime.html#date_trunc
- https://docs.snowflake.com/en/sql-reference/functions/date_trunc.html

For Snowflake, you need to override `SnowflakeMetriqlBridge.functions` because it looks like the parameters reversed in it: https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_trunc

SQL Server doesn't seem to implement date_trunc so we should probably don't support date_trunc in SQL server for now: https://stackoverflow.com/questions/53842817/date-trunc-month-in-sql-server

Let me know if you need help, we love contributions. :)

**Comment by AndreasTA-AW** [comment]
This seem to be blocking alot of queries coming from thoughtspot at least, since they use date_trunc alot

**Comment by buremba** [comment]
@minhlucvan are you willing to implement it? If not, I can assign it to myself.

**Comment by buremba** [comment]
It's implemented in `master` but we need to fix https://github.com/metriql/metriql/issues/57 ti make it work for all the cases in BigQuery
