### ISSUE TITLE
Cannot run program "gcloud"

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#46]
Hi,

I'm running with a profile that is using bigquery and a service account. But when I start the docker container it says "Cannot run program "gcloud"".  Is gcloud necessary even if I use a service account?

Cheers

**Comment by AndreasTA-AW** [comment]
Looked in the code and I don't specify the project. https://github.com/metriql/metriql/blob/master/src/main/java/com/metriql/warehouse/bigquery/BigQueryDataSource.kt#L82

Got another error when I did actually specify it:

Exception in thread "main" /root/.config/gcloud/application_default_credentials.json not found connecting the BigQuery.

**Comment by AndreasTA-AW** [comment]
Ok, so I used keyfile instead of keyFile, which DBT is fine with but not Metriql apparantly :) might be good to do a lowercase check on that one.

https://github.com/metriql/metriql/blob/master/src/main/java/com/metriql/warehouse/bigquery/BigQueryDataSource.kt#L71

**Comment by AndreasTA-AW** [comment]
keyfile has to be lowercase, otherwise I can't run DBT. Either I'm doing something wrong or you should change to lowercase by default.

**Comment by buremba** [comment]
Yes, you're right. There was a pending PR and it's now merged. Can you please try again? https://github.com/metriql/metriql/pull/43

**Comment by AndreasTA-AW** [comment]
I will try to do it during the day or tomorrow

**Comment by AndreasTA-AW** [comment]
Seems to work.
