### ISSUE TITLE
Connect via DBeaver when SSL

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#49]
Hi,

I've exposed MetriQL behind an ssl proxy and I can connect via the python library, but via DBeaver I get an exception when trying to connect.

```
Error starting query at https://some-domain.com/v1/statement returned an invalid response: JsonResponse{statusCode=500, statusMessage=, headers={access-control-allow-credentials=[true], access-control-allow-headers=[content-type,token], access-control-allow-origin=[*], content-length=[129], date=[Sun, 28 Nov 2021 06:46:36 GMT], samesite=[None; Secure], server=[openresty/1.19.9.1], strict-transport-security=[max-age=63072000]}, hasValue=false} [Error: {"errors":[{"id":null,"links":null,"status":null,"code":null,"title":"An error occurred","detail":null,"meta":null}],"meta":null}]
```

The server side says.

```
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, TABLE_TYPE, REMARKS,
TYPE_CAT, TYPE_SCHEM, TYPE_NAME,   SELF_REFERENCING_COL_NAME, REF_GENERATION
FROM system.jdbc.tables
WHERE TABLE_NAME LIKE '%' ESCAPE '\'
ORDER BY TABLE_TYPE, TABLE_CAT, TABLE_SCHEM, TABLE_NAME
javax.ws.rs.WebApplicationException: User must be set
io.trino.server.HttpRequestSessionContext.badRequest(HttpRequestSessionContext.java:503)
io.trino.server.HttpRequestSessionContext.assertRequest(HttpRequestSessionContext.java:452)
io.trino.server.HttpRequestSessionContext.buildSessionIdentity(HttpRequestSessionContext.java:223)
io.trino.server.HttpRequestSessionContext.<init>(HttpRequestSessionContext.java:120)
com.metriql.service.jdbc.StatementService.createSessionContext(StatementService.kt:95)
com.metriql.service.jdbc.StatementService.query$lambda-3(StatementService.kt:105)
```

**Comment by buremba** [comment]
Could you please send a screenshot of the connection page? The user is required, here is an example config:

<img width="585" alt="CleanShot 2021-11-28 at 14 16 14@2x" src="https://user-images.githubusercontent.com/82745/143765571-820fbd0e-d3c8-47c6-af1f-ff91edd3833f.png">

**Comment by AndreasTA-AW** [comment]
That's exactly how I set it up. I have a different username though. Could it be with the loadbalancer in front of it, or something else? I saw that if ssl is terminated before the server, Trino needs this config ```http-server.process-forwarded=true```. I've got no clue, just throwing idéas in the air :)

Seems it didn't work from thoughtspot either, so must be something wrong with my setup I guess.

**Comment by AndreasTA-AW** [comment]
Do you need any more info or do you think it's possible to debug anyway? :) I'll be happy to dig further if you need more info. We are currently running another trial where it would be fun to get metriql up and running.

**Comment by AndreasTA-AW** [comment]
Here is the full stacktrace at least
```
javax.ws.rs.WebApplicationException: User must be set
io.trino.server.HttpRequestSessionContext.badRequest(HttpRequestSessionContext.java:503)
io.trino.server.HttpRequestSessionContext.assertRequest(HttpRequestSessionContext.java:452)
io.trino.server.HttpRequestSessionContext.buildSessionIdentity(HttpRequestSessionContext.java:223)
io.trino.server.HttpRequestSessionContext.<init>(HttpRequestSessionContext.java:120)
com.metriql.service.jdbc.StatementService.createSessionContext(StatementService.kt:95)
com.metriql.service.jdbc.StatementService.query$lambda-3(StatementService.kt:105)
org.rakam.server.http.RakamHttpRequest.handleBody(RakamHttpRequest.java:250)
org.rakam.server.http.HttpServerHandler.handleBody(HttpServerHandler.java:162)
org.rakam.server.http.HttpServerHandler.channelRead(HttpServerHandler.java:112)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by AndreasTA-AW** [comment]
If I enter the wrong username I get Authentication failed, so it's getting there, but somehow fails.

**Comment by AndreasTA-AW** [comment]
Thoughtspot prints this in chrome console
```"debug":"[\"java.sql.SQLException: Authentication failed: Unauthorized\",\"\"]"```
I'm copying what I'm using in the python client.

**Comment by buremba** [comment]
Sorry for the delay, I believe that it's related to load-balancers `X-Forwarded-Proto` headers but I couldn't reproduce the issue. Let me work on it today and I will get back to you.

**Comment by AndreasTA-AW** [comment]
Seems I get "Authentication failed" instead now with the latest image. Python library still works though.

**Comment by buremba** [comment]
After spending an hour, I still couldn't reproduce the issue. Can you please answer the following questions?

1. Is the Metriql passwordless or did you set up username & password authentication? If you try running it in passwordless mode, does it work?

2. How do you set up the load balancer, is it a managed service? I suspect that it might be re-writing all the headers with `X-`Forwarded-` prefix.

3. How do you use the Python library, can you send the snippet here?

Once you answer the questions, I will deep dive and try to solve the issue tomorrow.

**Comment by AndreasTA-AW** [comment]
1. It has a password. Not to keen to expose it without actually :)
2. Now I'm setting up an Nginx and a separate VM for this. UI works, python library works, DBEaver gets unauthorized or that it tries to use http in the next call, instead of https. Depending on what I change. Headers are being proxied with X-Forwarded- indeed, shouldnt that be the case?
3. 

```
import trino

METRIQL_HOST = 'mydomain.com'
METRIQL_PORT = '443'
YOUR_METRIQL_USERNAME = 'username'
YOUR_METRIQL_PASSWORD = 'supersecret'

conn = trino.dbapi.connect(
    http_scheme="HTTPS",
    host=METRIQL_HOST,
    port=METRIQL_PORT,
    user=YOUR_METRIQL_USERNAME,
    catalog='metriql',
    schema='public',
    auth=trino.auth.BasicAuthentication(YOUR_METRIQL_USERNAME, YOUR_METRIQL_PASSWORD),
)
cur = conn.cursor()
all_datasets = cur.execute('SHOW TABLES')
print(cur.fetchall())

cur.execute("""
    select * from "ref('some_table')"
""")

print(cur.fetchall())

**Comment by AndreasTA-AW** [comment]
@buremba If it works for you when you do SSL termination in NGINX in front of a secured MetriQL instance protected with username/password, could you please share that configuration?

**Comment by AndreasTA-AW** [comment]
DBeaver is actually doing things my the look of it when I try to connect, but I still get unauthorized. The metriql logs say

```
SELECT TYPE_NAME, DATA_TYPE, PRECISION, LITERAL_PREFIX, LITERAL_SUFFIX,
CREATE_PARAMS, NULLABLE, CASE_SENSITIVE, SEARCHABLE, UNSIGNED_ATTRIBUTE,
FIXED_PREC_SCALE, AUTO_INCREMENT, LOCAL_TYPE_NAME, MINIMUM_SCALE, MAXIMUM_SCALE,
SQL_DATA_TYPE, SQL_DATETIME_SUB, NUM_PREC_RADIX
FROM system.jdbc.types
ORDER BY DATA_TYPE

SELECT TABLE_CAT
FROM system.jdbc.catalogs
ORDER BY TABLE_CAT

SELECT TABLE_SCHEM, TABLE_CATALOG
FROM system.jdbc.schemas
ORDER BY TABLE_CATALOG, TABLE_SCHEM
```

**Comment by AndreasTA-AW** [comment]
Isn't this line messing things up? 
https://github.com/metriql/metriql/blob/master/src/main/java/com/metriql/service/jdbc/StatementService.kt#L211

**Comment by buremba** [comment]
Wow, that's strange. Our HTTPS workloads work maybe because HTTP redirects to HTTPS and we didn't realize it. Let me work on it know, will get back to you in an hour.

**Comment by buremba** [comment]
@AndreasTA-AW , we don't want to require the Metriql URL as a parameter when you run the `serve` command and Metriql itself doesn't really support SSL. You need to have a load balancer to support HTTPS in Metriql which passes `X-Forwarded-Proto` to the Metriql instance. We cover this use-case now, it's in the `metriql:latest`:
Relevant commit: https://github.com/metriql/metriql/commit/4554e2a30cc29b388df66e5768ddedf0d45764f1

**Comment by buremba** [comment]
Can you try and let me know if you run into any issues?

**Comment by AndreasTA-AW** [comment]
Will test it out. That’s the way I wanted it to be :)

**Comment by AndreasTA-AW** [comment]
Works like a charm
