### ISSUE TITLE
Support TIMESTAMP '' in where

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#50]
Thoughtspot generates queries on timestamps like below
```
WHERE (
  "ta_1"."booked_date" >= TIMESTAMP '2021-01-01 00:00:00.0'
)
```

But this is currently not supported in metriql, I guess it should be?

**Comment by AndreasTA-AW** [comment]
Anything I can do here? This is kind of blocking our evaluation :)

**Comment by buremba** [comment]
@AndreasTA-AW, I'm on it. :) It should be implemented this week.

**Comment by AndreasTA-AW** [comment]
Sweet! Thanks for the quick response

**Comment by buremba** [comment]
Thanks!
