### ISSUE TITLE
GROUP BY

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#54]
Hi, 

Group by seems to not work that great. If using any aggregation it usually fails

```
SELECT 
  "ta_1"."some_field" "ca_1", 
  count("ta_1"."total_orders") "ca_2", 
  avg("ta_1"."some_field_2") "ca_3"
FROM "metriql"."public"."model_some" "ta_1"
GROUP BY "ta_1"."some_field"
```

```
SELECT list expression references column some_field which is neither grouped nor aggregated at [1:8]
SELECT some_field AS `ca_1`, `total_orders` AS `ca_2`, avg(some_field_2) AS `ca_3` FROM (
SELECT 
    `model_some`.`some_field` AS `some_field`,
    `model_some`.`some_field_2` AS `some_field_2`,
    count(1) AS `total_orders`
FROM `project`.`mart`.`table` AS `model_some`

    GROUP BY
    1,  2 

) AS `ta_1` 
```

**Comment by buremba** [comment]
The query seems to be fine actually, which data warehouse is it?

**Comment by AndreasTA-AW** [comment]
It's bigquery, this one looks kind of OK, but gives the error as shown.
Sometimes the grouping is not added at all I think.

**Comment by buremba** [comment]
Do you have something reproducible like an MQL query that I can use myself? Also, please share the data models if possible so that I can understand the cases where the GROUP BY is not generated.

**Comment by buremba** [comment]
I believe that the issue is resolved now. Feel free to re-open if you run into the same issue. Thanks!
