### ISSUE TITLE
Error when using "where col = true" with boolean

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#64]
When I’m trying to do a simple query like:
```
select total_meetings from "ref('meetings')" 
where is_sales_meeting = false -- or true 
```

I get this error
```
SQL Error [10]: Query failed (#52409516-4563-44e8-903a-b0867351fdb9): `equals` is not valid, valid values are `IS`
null
```

**Comment by santi95** [comment]
Try 

```
select total_meetings from "ref('meetings')" 
where is_sales_meeting **is** false -- or true 
```

**Comment by AndreasTA-AW** [comment]
I can test it, will a bi tool call it like that?

**Comment by AndreasTA-AW** [comment]
Aah sorry, i saw the double starts in the mail.
I’ve tried ”is” as well if I remember correct, but will double check

**Comment by buremba** [comment]
I thought that Trino only supports `col1 is true` but after a quick test, it looks like `col1 = true` is also a valid syntax so I will add this option to make the query work.
