### ISSUE TITLE
Dbt metricw

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#67]
Cube has an idea of how to solve multiple measures in the same model for DBT. Maybe something to look at?
https://github.com/cube-js/cube.js/issues/3611

**Comment by buremba** [comment]
Hey @AndreasTA-AW , unfortunately the suggested idea breaks `time_grains` and `dimensions` as each metric has its own set of dimensions in dbt metric definitions. Merging all the metrics into the same model sounds more compact but this is not the dbt's metrics vision in my opinion. For now, I believe that it's best to have one metric for each dataset in case you use dbt's metric definitions but we will keep supporting `mode.meta.metriql` in case you want to define multiple metrics under same dataset. What do you think?

**Comment by AndreasTA-AW** [comment]
Yeah, that works. It would be nice to follow native dbtonic style though to be able to follow their documentation. It gets a bit spread out otherwise, but it is fine

**Comment by buremba** [comment]
Yes, you're right. Feel free to open the issue if you would like to discuss further
